// Song is the canonical shape used everywhere in the app.
// instrument_names and tags are always JS arrays here (never raw JSON strings) —
// the serialisation to/from TEXT happens exclusively in db.ts (rowToSong / PATCH).
export interface Song {
  id: number;
  // filename: UUID-based name on disk (e.g. "3f2e...uuid.mid"). Never exposed in UI.
  filename: string;
  // original_name: the filename as uploaded by the user, shown in the UI.
  original_name: string;
  title: string;
  artist: string;
  instrument: string;
  genre: string;
  mood: string;
  folder: string;
  difficulty: string;
  duration_sec: number;
  tempo_bpm: number;
  track_count: number;
  note_count: number;
  // format: MIDI file format (0 = single track, 1 = multi-track, 2 = multi-song).
  format: number;
  // ticks_per_qn: MIDI resolution (pulses per quarter note). Needed to convert
  // raw tick values to real-time seconds during playback.
  ticks_per_qn: number;
  instrument_names: string[];
  key_signature: string;
  time_signature: string;
  // "direct" = note-for-note transcription; "arrangement" = adapted for a different
  // instrument or style. Stored as TEXT in SQLite, validated as a union type here.
  transcription_type: "direct" | "arrangement";
  tags: string[];
  // is_favorite is stored as INTEGER 0/1 in SQLite; rowToSong coerces it to boolean.
  is_favorite: boolean;
  play_count: number;
  last_played: string | null;
  share_count: number;
  ai_summary: AISummary | null;
  created_at: string;
}

// AISummary is generated by Groq and stored as serialised JSON in songs.ai_summary.
// The structure is driven by the prompt in groq.ts — changing field names here
// requires updating the prompt to match.
export interface AISummary {
  facts: string[];
  tips: string[];
  related: { title: string; artist: string; reason: string }[];
}

export interface MidiMetadata {
  duration_sec: number;
  tempo_bpm: number;
  track_count: number;
  note_count: number;
  format: number;
  ticks_per_qn: number;
  instrument_names: string[];
}

// WizardData is the shape passed between UploadWizard steps and sent to POST /api/songs.
export interface WizardData {
  filename: string;
  original_name: string;
  midi: MidiMetadata;
  title: string;
  artist: string;
  instrument: string;
  genre: string;
  mood: string;
  difficulty: string;
  folder: string;
  // tags is a raw comma-separated string here (wizard textarea input) and is split
  // into an array server-side on POST. PATCH /api/songs/:id expects a pre-split array.
  tags: string;
  key_signature: string;
  time_signature: string;
  transcription_type: "direct" | "arrangement";
  target_instrument?: string;
}
